[package]
name = "gremlin-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
bytes = "1"
http = "1"
url = "2"
thiserror = "1"
tokio = { version = "1", features = ["fs", "io-util"] }
